# Generated by Django 2.0.3 on 2018-03-22 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No title', max_length=500)),
                ('answer_posted_by', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('total_up_vote', models.IntegerField(default=0, null=True)),
                ('total_down_vote', models.IntegerField(default=0, null=True)),
                ('total_points', models.IntegerField(default=0, null=True)),
                ('tags', models.CharField(default='No Tags', max_length=500)),
                ('last_updated_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'answers',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No title', max_length=500)),
                ('question_posted_by', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('total_up_vote', models.IntegerField(default=0, null=True)),
                ('total_down_vote', models.IntegerField(default=0, null=True)),
                ('total_points', models.IntegerField(default=0, null=True)),
                ('tags', models.CharField(default='No Tags', max_length=500)),
                ('last_updated_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='QuestionsAnswersRankHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_vote', models.IntegerField(default=0, null=True)),
                ('down_vote', models.IntegerField(default=0, null=True)),
                ('total_points', models.IntegerField(default=0, null=True)),
                ('coin_credited', models.FloatField(default=0, null=True)),
                ('coin_debited', models.FloatField(default=0, null=True)),
                ('last_updated_time', models.DateTimeField(auto_now_add=True)),
                ('answer_id',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='community.Answers')),
                ('question_id',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='community.Questions')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'question_answer_rank_history',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_question_up_voted', models.BooleanField(default=False)),
                ('is_question_down_voted', models.BooleanField(default=False)),
                ('is_answer_up_voted', models.BooleanField(default=False)),
                ('is_answer_down_voted', models.BooleanField(default=False)),
                ('answer_id',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='community.Answers')),
                ('question_id',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='community.Questions')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vote',
            },
        ),
        migrations.AddField(
            model_name='answers',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_object',
                                    to='community.Questions'),
        ),
        migrations.AddField(
            model_name='answers',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
