name: dvs_hybrid
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  url_launcher: "^3.0.0"
  flutter_localstorage:
     git:
       url: git://github.com/lakexyde/flutter_localstorage.git
  flutter_circular_chart:
    git:
      url: git://github.com/xqwzts/flutter_circular_chart.git
      
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/background.jpg
     - assets/icn_app_logo.png
     - assets/tab_dashboard.png
     - assets/tab_settings.png
     - assets/icn_logout.png
     - assets/icn_management.png
     - assets/icn_privacy.png
     - assets/icn_profile.png
     - assets/icn_terms.png
     - assets/tab_wallet.png
     - assets/icn_support.png
     - assets/icn_password.png
     - assets/bg/header.jpg
     - assets/bg/bsp_header.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
