<?php

namespace utilities\constant;

class InputFieldLengthConstant {
	
	//user
	const USER_USER_NAME_MAX_LENGTH = 45;
	const USER_COUNTRY_CODE_MAX_LENGTH = 3;
	const USER_EMAIL_ADDRESS_MAX_LENGTH = 100;
	const USER_MOBILE_NUMBER_MAX_LENGTH = 15;
	const USER_VERIFICATION_CODE_MAX_LENGTH = 4;
	const USER_DEVICE_ID_MAX_LENGTH = 100;
	const USER_DEVICE_NOTIFICATION_KEY_MAX_LENGTH = 255;
	
	//social group
	const SOCIAL_GROUP_NAME_MAX_LENGTH = 50;
	
	//media
	const MEDIA_CONTENT_TYPE_MAX_LENGTH = 50;
	const MEDIA_FILE_EXTENSION_MAX_LENGTH = 10;
	
}